// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace ExampleApplication.Data.Entities
{
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.2.0")]
    public class Country
    {
        public Guid Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<RadioStation> RadioStations { get; set; }
        
        public Country()
        {
            Id = System.Guid.NewGuid();
            RadioStations = new List<RadioStation>();
        }
    }

}
// </auto-generated>
