SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Countries] (
	[ID] uniqueidentifier NOT NULL DEFAULT NEWID(),
	[Name] NVARCHAR(200) NOT NULL,
 CONSTRAINT [PK_Countries] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

INSERT INTO [dbo].[Countries](Name) VALUES('United Kindgom');
INSERT INTO [dbo].[Countries](Name) VALUES('France');
INSERT INTO [dbo].[Countries](Name) VALUES('Poland');

GO
